# Etapa base: instala dependencias
FROM node:20-alpine AS base
WORKDIR /app
COPY package.json yarn.lock* ./
RUN yarn install --frozen-lockfile

FROM base AS dev
WORKDIR /app
COPY . .


ENV HOST=0.0.0.0
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true
EXPOSE 3000

CMD ["yarn", "dev", "--hostname", "0.0.0.0"]

FROM base AS build
WORKDIR /app
COPY . .
RUN yarn build

FROM node:20-alpine AS final
WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app/public ./public
COPY --from=build /app/.next ./.next
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json

EXPOSE 3000
CMD ["yarn", "start"]
