FROM node:20-alpine AS dev
WORKDIR /app

COPY package.json yarn.lock* ./

RUN yarn install --frozen-lockfile

ENV HOST=0.0.0.0
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

EXPOSE 3000

CMD ["yarn", "dev", "--hostname", "0.0.0.0"]

