FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
WORKDIR /src

COPY . .

EXPOSE 8080

CMD ["dotnet", "watch", "--project", "MillionProperty.API/MillionProperty.API.csproj", "run", "--urls", "http://*:8080"]
